### PR TITLE
Feature: Open search with cmd/ctrl-k

### PR DESCRIPTION
**Pull request by andysm1th**
Closes #37: Implemented keyboard shortcut for opening/closing search with cmd/ctrl-k

- Reworked structure of the client folder and abstracted out functionality to improve readability
- Added new hook to add aria-keyshorcuts attribute to autocompletes dynamically generated combobox
- Abstracted autocomplete initialisation into new hook
- Added new hook to setup the required keyboard shortcut event. This is used on state change to determine the current state of the search box.
- Added new icons to show to user the shortcut is available. Similar to Algolia's style.
- Minor style amends
- Renamed `shared.ts` to `constants.ts`
- Removed unused `useFetchIndex` hook
- Removed unused `styles.modules.css`

**Testing Notes:**

There is no easy way to setup and work with this plugin locally (tried a variety of methods). The simplest method to test these client changes is first to setup a local instance of Docusaurus with:

`npx create-docusaurus@latest docsaurus-ts classic --typescript`

Next install this package: `npm install --save @lyrasearch/plugin-docusaurus`

And add the plugin to your docusaurus.config.js:

`plugins: ["@lyrasearch/plugin-docusaurus"]`

Now from this PR's branch, copy the folder `/src/client/theme/SearchBar` to the Docusaurus folder `src/theme/SearchBar` to override it. This is effectively overriding the default client template provided by this plugin.

Due to the nature of this repos setup you'll have to correct some import paths.

A quick find on `.js'` and replace with `'` should get you going.

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Wow there's lots of stuff in here. Very hard to figure out what these changes may do without actually running the app. Can you put some testing instructions in the PR body so somebody reviewing knows how to try this out, and maybe mention something to watch out for that you may be concerned your changes may have broken?

**Comment by simoneb** [comment]
@andysm1th isn't the sandbox included in the repo working anymore?

**Comment by simoneb** [comment]
also, CI is failing, can you take a look?

**Comment by andysm1th** [comment]
@simoneb No the sandbox doesn't seem to be working. This is why the build is failing too.

**Comment by simoneb** [comment]
> @simoneb No the sandbox doesn't seem to be working. This is why the build is failing too.

I think that's supposed to be _the_ way to test the plugin, so can we get it back to working, unless there are good reasons why it shouldn't work, in which case I guess we should consider removing it altogether?

**Comment by andysm1th** [comment]
I'll take a look at it, there seems to be some missing files. Looking back through the history the build seems to have been failing on PRs for quite some time

**Comment by simoneb** [comment]
I tried testing this in the sandbox and I couldn't as I don't know what to expect exactly. I can see a fairly broken UI shown, with indication that there is a CMD/CTRL+k key that can be used:

image

The key combination does bring up a search window, but it also conflicts with browser default behavior which puts focus on the search bar:

image

I think we should improve the overall status of this package as part of this change, but having a sandbox which works properly. Also setting up the sandbox requires some work, as it references the plugin packed in a tgz file, but there are no instructions about how to do that. It would be useful to have some automation scripts and some docs around this.

**Comment by simoneb** [comment]
Oh, note that the key combination works just fine on other websites built with docusaurus, such as https://create-react-app.dev/, in the sense that it doesn't conflict with other key bindings.

**Comment by andysm1th** [comment]
Hi @simoneb, sounds good. I've already been looking at improving the sandbox for local development so I'll continue.

In terms of using it now, our custom styles aren't currently loading, this is why the output is un-styled. This is also the case if you run a packaged copy of the main branch in the sandbox. It could potentially be related to the use of peer dependencies with pnpm and the docusaurus theme. I'll investigate.

I cannot replicate the issue you're having with the shortcut. Are you sure you aren't hitting cmd+l by accident? This is directly next to k on the keyboard and this puts focus on the browsers search bar. I've done it myself a few times!

**Comment by simoneb** [comment]
> I cannot replicate the issue you're having with the shortcut. Are you sure you aren't hitting cmd+l by accident? This is directly next to k on the keyboard and this puts focus on the browsers search bar. I've done it myself a few times!

Yes I'm sure, I'm on windows. CTRL+L puts the focus on the search bar, whereas CTRL+K opens up the default search engine in the search bar (basically 2 different behaviors). The CTRL+K behavior doesn't happen in the CRA website and CTRL+K is handled correctly by the search within the docusaurus app instead. There might be some sort of overriding going on

**Comment by andysm1th** [comment]
Closing this PR as it is now superceded by https://github.com/LyraSearch/plugin-docusaurus/pull/96

**Pull request closed without merging**
