### PR TITLE
chore: Fixed release build.

### PR DESCRIPTION
**Pull request by ShogunPanda**

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
for consistency with the version scheme, we probably also want this https://github.com/LyraSearch/lyra/blob/main/.github/workflows/release.yml#L36

**Comment by simoneb** [comment]
also note that the prerelease-prefix input to the release action is hardcoded to beta. I think it would be best to make it a workflow input instead

**Comment by ShogunPanda** [comment]
@simoneb  Added both.

**Review by Ceres6 — APPROVED** [review]
LGTM!

**Pull request merged**
