### PR TITLE
chore: change to pnpm

### LINKED ISSUE #59: fix publish errors

### PR DESCRIPTION
**Pull request by Ceres6**
closes #59 

* Change to pnpm 
* Solved publish problems

_NOTE_: I could add Verdaccio e2e test to verify publishes

### CODE REVIEW

**Review by simoneb — COMMENTED** [review]
Is this intended to address the publishing issues as well? Asking because if that's the case, I don't see enough changes in this PR to fix that issue

**Comment by Ceres6** [comment]
> Is this intended to address the publishing issues as well? Asking because if that's the case, I don't see enough changes in this PR to fix that issue

Why do you think that? I tried publishing it with Verdaccio and it worked. The thing that solved it was having the `publishDirectory` set to the plugin one.

**Review by simoneb — APPROVED** [review]
LGTM

**Review by micheleriva — APPROVED** [review]
LGTM

**Pull request merged**
